import { Injectable } from '@angular/core';
import { GoogleGenAI, GenerateImagesResponse, Type } from '@google/genai';

@Injectable({
  providedIn: 'root'
})
export class GeminiService {
  private readonly ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      throw new Error('API_KEY environment variable not set');
    }
    this.ai = new GoogleGenAI({ apiKey });
  }

  async generateCharacterImage(prompt: string): Promise<string> {
    try {
      const response: GenerateImagesResponse = await this.ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '1:1',
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const image = response.generatedImages[0];
        if (image.image && image.image.imageBytes) {
          return image.image.imageBytes;
        }
      }
      throw new Error('No image was generated by the API.');
    } catch (error) {
      console.error('Error generating image with Gemini API:', error);
      throw new Error('The AI failed to visualize the character. Please try a different description.');
    }
  }

  async generateCharacterTraits(prompt: string): Promise<string[]> {
    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              traits: {
                type: Type.ARRAY,
                items: {
                  type: Type.STRING,
                  description: 'A single personality trait.'
                }
              }
            },
            required: ['traits']
          },
          temperature: 0.8,
        }
      });

      const jsonString = response.text.trim();
      const result = JSON.parse(jsonString);

      if (result.traits && Array.isArray(result.traits)) {
        return result.traits.slice(0, 3); // Ensure we only take up to 3 traits
      }

      throw new Error('Invalid format for traits received from API.');
    } catch (error) {
      console.error('Error generating character traits with Gemini API:', error);
      throw new Error('The AI failed to generate character traits.');
    }
  }
}